### ISSUE TITLE
Targetcli fails to start

### ISSUE THREAD

**Issue by neomerx** [open-iscsi/targetcli-fb#123]
```bash
$ targetcli
```

output

> Traceback (most recent call last):
  File "/usr/bin/targetcli", line 24, in <module>
    from targetcli import UIRoot
  File "/usr/lib/python3.7/site-packages/targetcli/__init__.py", line 18, in <module>
    from .ui_root import UIRoot
  File "/usr/lib/python3.7/site-packages/targetcli/ui_root.py", line 32, in <module>
    from .ui_backstore import complete_path, UIBackstores
  File "/usr/lib/python3.7/site-packages/targetcli/ui_backstore.py", line 20, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'

The headless server got no UI except console over SSH.

It used to work some time ago.

**Comment by maurizio-lombardi** [comment]
Hi, are you using a Debian system?

Can you check if the python3-gi package is installed on your system?

**Comment by neomerx** [comment]
I'm using arch.

I've followed your advice and added [python-gobject](https://www.archlinux.org/packages/extra/x86_64/python-gobject/) and it helped. So it looks like the bug is in [targetcli-fb](https://aur.archlinux.org/packages/targetcli-fb/) where they need to add the extra dependency.

**Comment by neomerx** [comment]
Added a comment about the missed dependency in the Arch repo. Hopefully, the maintainer adds the fix.
