### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/targetcli-fb#148]
Can you tag a new version of targetcli-fb please? The new daemon functionality is a bit of a jump from previous versions. I'd like to merge the new changes in our distribution's base, but it's much easier if I have a new tag to pull.

**Comment by maurizio-lombardi** [comment]
Hello, yes. I was already planning a new release for configshell/rtslib/targetcli this week

**Comment by gonzoleeman** [comment]
Excellent, thanks!

**Comment by maurizio-lombardi** [comment]
Done
