### ISSUE TITLE
Is it possible to export scsi generic changer devices too?

### ISSUE THREAD

**Issue by abbbi** [open-iscsi/targetcli-fb#158]
hi,

im using targetcli-fb on centos8 (2.1.fb49) in order to export mhvtl virtual tape devices, which works
flawlessly via the /backstores/pscsi backend. 

Is it also possible to export the generic loader device using pscsi? According to the documentation it should be possible the export all devices shown via lsscsi, but creating an backend for the loader device fails with:

```
/backstores/pscsi> create name=loader1 dev=/dev/sg7
Cannot configure StorageObject because device /dev/sg7 (SCSI 7:0:0:0) is already in use
```

so shouldnt this be possible too?

```
lsscsi -g | grep sg7
[7:0:0:0]    mediumx STK      L700             0105  /dev/sch0  /dev/sg7 
```

**Comment by abbbi** [comment]
Oh sorry, it appears such mappings must be created with /dev/sch0 instead of /dev/sg7, then it works flawlessly.

**Comment by abbbi** [comment]
hi, 

i think this might need some more discussion. The devices like /dev/sch0 are prone to be swapped amongst reboots, so they are not static reservations according to my info.

Would it be possible for targetcli to configure the represented static loader device from /dev/tape/by-id too?

**Comment by gonzoleeman** [comment]
Why can't you use the changer device node, i.e. /dev/sch0? If you have only one emulated tape driver, than that's going to be it. If you have more tape drives, then yes you will need to be more rigorous about which drive is which.

**Comment by abbbi** [comment]
I have multiple emulated tape and changer devices.

**Comment by asfethan** [comment]
We have multiple SL150 in our production environment and we faced this issue too. Actually I think the main issue lies in missing usable UDEV environment variables like model, serial number, wwn which you can read with udevadm utility but I am not 100% sure it's issue with "ch" driver (scsi_changer). With these variables we could create udev rules to make permanent naming work through symlinks and wwn or serial variables. This solution is related to "/dev/sch*" devices.

Although I think that exporting scsi_generic device should work too but I don't know why O_EXCL flag can't be set on that device. I tried to unload "ch" driver but still I got the same error.
