### ISSUE TITLE
LIO I/O lifecycle 

### ISSUE THREAD

**Issue by onkar6699** [open-iscsi/targetcli-fb#183]
anybody can explain how LIO works in detail like life cycle from initiator to target and which system call involved on target please if any article ??

**Comment by gonzoleeman** [comment]
This may be a dumb reply, but have you searched the internet? I found a bunch of references when searching for "linux kernel lio subsystem".

**Comment by onkar6699** [comment]
@gonzoleeman i searched on internet "linux kernel lio subsystem" but i got result like  "linux kernel IIO subsystem" if you found any then please forward here.thanks in advance

**Comment by gonzoleeman** [comment]
Strange, we must have different internets.

I get very relavent hits:

* https://en.wikipedia.org/wiki/LIO_(SCSI_target)
* http://linux-iscsi.org/wiki/LIO
* https://www.kernel.org/doc/html/latest/target/tcmu-design.html
* ...

Then there's lwn.net, which requires a subscription, but is well worth it:

* https://lwn.net/Articles/311346/

Then look at the sources of targetcli-fb (all in python).

Please come back when you've read all that. :)

Marking as closed.
