### ISSUE TITLE
Could not create Target in configFS

### ISSUE THREAD

**Issue by Giridhar547** [open-iscsi/targetcli-fb#190]
I am trying to setup LIO server for the first time
However its' failing with the below error 

All modules look loaded:

# lsmod | egrep -i "target|qla"
tcm_qla2xxx            40960  1
iscsi_target_mod      348160  1
target_core_user       49152  0
uio                    20480  1 target_core_user
target_core_pscsi      28672  0
target_core_file       28672  0
target_core_iblock     28672  2
target_core_mod       401408  11 target_core_file,target_core_iblock,iscsi_target_mod,tcm_qla2xxx,target_core_pscsi,target_core_user
configfs               57344  3 iscsi_target_mod,target_core_mod
qla2xxx               888832  1 tcm_qla2xxx
nvme_fc                49152  1 qla2xxx
scsi_transport_fc      69632  2 qla2xxx,tcm_qla2xxx
scsi_mod              258048  15 ses,scsi_dh_emc,scsi_transport_sas,sd_mod,dm_multipath,qla2xxx,scsi_dh_alua,scsi_transport_fc,tcm_qla2xxx,usb_storage,target_core_pscsi,uas,sg,smartpqi,scsi_dh_rdac

OS details:

 # cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

# uname -a
Linux  ... 5.3.18-22-default #1 SMP Wed Jun 3 12:16:43 UTC 2020 (720aeba) x86_64 x86_64 x86_64 GNU/Linux

Targetcli and rtslib versions:

# rpm -qa |egrep -i "target|rtslib"
targetcli-fb-common-2.1.52-1.5.noarch
python3-targetcli-fb-2.1.52-1.5.noarch
python3-rtslib-fb-2.1.71-1.21.noarch

Able to create block datastores:

/> ls
o- / ........................................................................................................................ [...]
  o- backstores ............................................................................................................. [...]
  | o- block ................................................................................................. [Storage Objects: 1]
  | | o- sdb ......................................................................... [/dev/sdb (745.2GiB) write-thru deactivated]
  | |   o- alua .................................................................................................. [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ...................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................ [Storage Objects: 0]
  | o- pscsi ................................................................................................. [Storage Objects: 0]
  | o- ramdisk ............................................................................................... [Storage Objects: 0]
  | o- rbd ................................................................................................... [Storage Objects: 0]
  o- iscsi ........................................................................................................... [Targets: 0]
  o- loopback ........................................................................................................ [Targets: 0]
  o- qla2xxx ......................................................................................................... [Targets: 0]
  o- vhost ........................................................................................................... [Targets: 0]
  o- xen-pvscsi ...................................................................................................... [Targets: 0]

However it's failing while creating target wwn:

/> /qla2xxx info
Fabric module name: qla2xxx
ConfigFS path: /sys/kernel/config/target/qla2xxx
Allowed WWN types: naa
Allowed WWNs list: naa.51402ec01486afc6, naa.51402ec01486afc4
Fabric module features: acls
Corresponding kernel module: tcm_qla2xxx
/> /qla2xxx create naa.51402ec01486afc6
Could not create Target in configFS

@maurizio-lombardi 

I see that previously you assisted in similar thread , Can you please take a look into what is wrong/that i am doing wrong 
Any help would be greatly appreciated 

Please let me know if any further details are needed

**Comment by maurizio-lombardi** [comment]
@Giridhar547 Do you see an error in dmesg?
I see you closed this issue, you solved it already?

**Comment by Giridhar547** [comment]
@maurizio-lombardi 

Yes , i relooked into the previous thread where you assisted and saw the following 

>>

I checked per the link http://www.linux-iscsi.org/wiki/Fibre_Channel#Enable_target_mode to ensure that I have initiator mode disabled

# cat /sys/module/qla2xxx/parameters/qlini_mode
disabled

In my case it was enabled and a bit more googling helped me to disable it by placing "options qla2xxx qlini_mode="disabled" via "/etc/modprobe.d/99-local.conf" in SLES and rebuilt the initramfs using dracut , rebooted the server and it started working

Thanks for looking into it though
