### ISSUE TITLE
Question: why can't i manually tweak etc/rtslib-fb-target/saveconfig.json ?

### ISSUE THREAD

**Issue by TMLKyza** [open-iscsi/targetcli-fb#208]
Hi, I'm just playing around and learning about iscsi.
I set up a 2 iqn setup on fileio and wanted to expand one of the 2 drives.

So my first idea was to truncate the fileio img file (no worries its on a zfs pool so i can always rollback) and then prompt a rescan on targetcli of the file size. 
Searching online it seems to be what people do on truenas, [see here](https://www.truenas.com/community/threads/resizing-a-file-based-iscsi-extent.35745/) but then they are able to prompt the file size rescan which I'm not able to!

My second idea was to manually change targetcli config file `/etc/rtslib-fb-target/saveconfig.json` such that 

```
      },
      "dev": "/tank/iscsi_img/tmlkyza.img",
      "name": "tmlkyza_library",
      "plugin": "fileio",
      "size": 536870912000, -----> "size": 644245094400,
      "write_back": true,
      "wwn": "4c43a6dd-9902-4f8b-b265-0d6b17499cc2"
    }
```
where i replaced the original size with the current one
```
total 309723219
drwxr-xr-x 2 cifs cifs            4 Nov 17 11:29 .
drwxr-xr-x 6 root root            6 Nov  9 17:44 ..
-rw-r--r-- 1 root root 536870912000 Nov 17 12:02 fra_disk.img
-rw-r--r-- 1 root root 644245094400 Nov 17 11:35 tmlkyza.img
```

The problem is whenever I launch targetcli to check the img size, this doesn't change and the file gets overwritten with the 500Gb config (a feature that I could turn off but I don't want to) 

I guess I'm missing something, is there a way to show targetcli that the img size has changed, so that i can restart the iscsi initiatior on my machine and expand the ext4 partition?

PS the targetcli version is:
```
/> version 
targetcli version 2.1.53
```

Many thanks for everyone's time!

EDIT:
changed the title to better describe the problem, as now I'm trying to tweak the MaxConnections parameters without success.
The behaviour is the same, the file gets overwritten each time

**Comment by gonzoleeman** [comment]
On Nov 17, 2024, at 3:07 AM, TMLKyza ***@***.***> wrote:
> 
> 
> Hi, I'm just playing around and learning about iscsi.
> I set up a 2 iqn setup on fileio and wanted to expand one of the 2 drives.
> 
> So my first idea was to truncate the fileio img file (no worries its on a zfs pool so i can always rollback) and then prompt a rescan on targetcli of the file size.
> Searching online it seems to be what people do on truenas, see here <https://www.truenas.com/community/threads/resizing-a-file-based-iscsi-extent.35745/> but then they are able to prompt the file size rescan which I'm not able to!
> 
> My second idea was to manually change targetcli config file /etc/rtslib-fb-target/saveconfig.json such that
> 
>       },
>       "dev": "/tank/iscsi_img/tmlkyza.img",
>       "name": "tmlkyza_library",
>       "plugin": "fileio",
>       "size": 536870912000, -----> "size": 644245094400,
>       "write_back": true,
>       "wwn": "4c43a6dd-9902-4f8b-b265-0d6b17499cc2"
>     }
> where i replaced the original size with the current one
> 
> total 309723219
> drwxr-xr-x 2 cifs cifs            4 Nov 17 11:29 .
> drwxr-xr-x 6 root root            6 Nov  9 17:44 ..
> -rw-r--r-- 1 root root 536870912000 Nov 17 12:02 fra_disk.img
> -rw-r--r-- 1 root root 644245094400 Nov 17 11:35 tmlkyza.img
> The problem is whenever I launch targetcli to check the img size, this doesn't change and the file gets overwritten with the 500Gb config (a feature that I could turn off but I don't want to)
> 
> I guess I'm missing something, is there a way to show targetcli that the img size has changed, so that i can restart the iscsi initiatior on my machine and expand the ext4 partition?
> 
> PS the targetcli version is:
> 
> /> version 
> targetcli version 2.1.53
> Many thanks for everyone's time!
> 

You need to save then clear the configuration from targetcli, edit the saveconfig.json file, then restore the config (assuming you’ve already made your backing store file/disk larger or smaller):

# targetcli / saveconfig /etc/target/temp.json
# targetcli / clearconfig true
# vi /etc/target/temp.json (change the “size” attribute)
# targetcli / restoreconfig /etc/target/temp.json

It should now have the new size. Check with “targetcli ls /“.

This worked for me.

Note: this assume you do not have the targetclid daemon running. I don’t use it, but if you do, you may have to stop the service before you edit the JSON file, then restart it, since I believe the daemon hold onto state.

— 
Lee Duncan

**Comment by TMLKyza** [comment]
oh i see now i understood, i wasn't killing the daemon thinking that by reloading the config file it would restart the daemon too.
Many thanks and sorry for the time!
