### ISSUE TITLE
Errno 20: Not a directory when trying to delete backstores/block 

### ISSUE THREAD

**Issue by java-juggled-jazz** [open-iscsi/targetcli-fb#209]
OS: Astra Linux (Debian-like)
Kernel Version: 6.1.50-1-generic

>Traceback (most recent call last):
>  File "/usr/bin/targetcli", line 329, in <module>
>    main()
>  File "/usr/bin/targetcli", line 317, in main
>    shell.run_interactive()
>  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 905, in run_interactive
>    self._cli_loop()
>  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 734, in _cli_loop
>    self.run_cmdline(cmdline)
>  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 848, in run_cmdline
>    self._execute_command(path, command, pparams, kparams)
>  File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 823, in _execute_command
>    result = target.execute_command(command, pparams, kparams)
>  File "/usr/lib/python3/dist-packages/configshell_fb/node.py", line 1406, in execute_command
>    return method(*pparams, **kparams)
>  File "/usr/lib/python3/dist-packages/targetcli/ui_backstore.py", line 309, in ui_command_delete
>    child.rtsnode.delete(save=save)
>  File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 269, in delete
>    for lun in self._gen_attached_luns():
>  File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 215, in _gen_attached_luns
>    for tpgt_dir in listdir(tpgts_base):
>NotADirectoryError: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'

**Comment by gonzoleeman** [comment]
On Nov 20, 2024, at 8:06 AM, Kamil ***@***.***> wrote:
> 
> 
> OS: Astra Linux (Debian-like)
> Kernel Version: 6.1.50-1-generic
> 
> Traceback (most recent call last): File "/usr/bin/targetcli", line 329, in <module> main() File "/usr/bin/targetcli", line 317, in main shell.run_interactive() File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 905, in run_interactive self._cli_loop() File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 734, in _cli_loop self.run_cmdline(cmdline) File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 848, in run_cmdline self._execute_command(path, command, pparams, kparams) File "/usr/lib/python3/dist-packages/configshell_fb/shell.py", line 823, in _execute_command result = target.execute_command(command, pparams, kparams) File "/usr/lib/python3/dist-packages/configshell_fb/node.py", line 1406, in execute_command return method(*pparams, **kparams) File "/usr/lib/python3/dist-packages/targetcli/ui_backstore.py", line 309, in ui_command_delete child.rtsnode.delete(save=save) File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 269, in delete for lun in self._gen_attached_luns(): File "/usr/lib/python3/dist-packages/rtslib_fb/tcm.py", line 215, in _gen_attached_luns for tpgt_dir in listdir(tpgts_base): NotADirectoryError: [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list’
> 

Note for the future: if you post this “quoted” (i.e. lines start with “> “), then I would be able to read it.

But I’m guessing you are running a really old kernel?

It looks like rtslib puked because /sys/kernel/config/target/iscsi/cpus_allowed_list is not available.

What do you have in /sys/kernel/config/target/iscsi?

What distribution and kernel are you running?

And what version of targetcli, rtslib, and configshell?

— 
Lee Duncan

**Comment by java-juggled-jazz** [comment]
Seems like the only way to fix it is force delete partition (I've used fdisk) and reboot system. Module won't find partition and delete it from configuration. I could probably just delete targetctl configs and their backups, but I've not checked

!!! DON'T FORGET TO BACK UP !!!
To back up you can use iSCSI-initiator or just dd utility

**Comment by maurizio-lombardi** [comment]
> [Errno 20] Not a directory: '/sys/kernel/config/target/iscsi/cpus_allowed_list'

I remember this error, it was due to some kernel changes if I remember correctly, let me see if I can find the root cause

**Comment by maurizio-lombardi** [comment]
> python-rtslib-fb: 2.1.71-3

Got it, @java-juggled-jazz Astra Linux should try to update to rtslib 2.1.75 (or backport the patch to the rtslib version they currently use)

The rtslib patch I am talking about has commit-id 8d2543c4da62e962661011fea5b19252b9660822
"handle target kernel module new attribute cpus_allowed_list"

**Comment by maurizio-lombardi** [comment]
> Seems like the only way to fix it is force delete partition (I've used fdisk) and reboot system.

No, this is not a solution, you will hit it again soon or later

**Comment by java-juggled-jazz** [comment]
> Got it, @java-juggled-jazz Astra Linux should try to update to rtslib 2.1.75 (or backport the patch to the rtslib version they currently use)
> 
> The rtslib patch I am talking about has commit-id 8d2543c4da62e962661011fea5b19252b9660822 "handle target kernel module new attribute cpus_allowed_list"

Thanks. I'll try this and get back a bit later with results
