### ISSUE TITLE
resizing the lun exposed by tcmu-runner

### ISSUE THREAD

**Issue by agrover** [open-iscsi/targetcli-fb#62]
I was emailed a request (below) for resizable tcmu backstores, but I'm not sure the degree we support resizing kernel-based backstores. We need to understand better the capabilities and implement support for both kinds to be resized. Here's the email:

```
It will be super cool, if we could introduce a resize option for the
LUN exposed from gluster volume as a backing store.

Currently I have done this manually with below steps,

Assuming the LUN was created with size 8G  and already in use by an initiator
1. umount the device and logout from the initiator
       # umount /mnt
       # multipath -F
       # iscsiadm -m node --logout

2. expand the target file size (on nodes belong to gluster volume)
       # mount -t glusterfs 10.70.42.151:/iscsi-store /mnt
       # truncate -s +2G /mnt/app-store.img
       # umount /mnt
       # Edit /etc/target/saveconfig to have new size 10G in
storage_objects -> "size": 10737418240'
       # systemctl restart target

3. login to iscsi target from initiator node and
       # iscsiadm -m discovery -t st -p 10.70.42.151 -l
       # parted -l /dev/sda (notice the target size changed)
       # mount /dev/sda /mnt -o sync
       # df -Th   (notice fs size is still 8G)
       # xfs_growfs  /dev/sda
       # df -Th (Boom!! see the grown xfs layout size to 10G)
```

**Comment by agrover** [comment]
If the target's backing file size changes then I think if the new size "dev_size=<new_size>" is written to /sys/kernel/config/target/core/$HBA/$dev/control then that may do the trick for LIO and tcmu to pick up the new size. Target restart should not be needed.

For testing purposes, does that work?? Of course we'd want a better UX for doing this but that'll at least indicate if doing the above is sufficient or not. We'd want a nice way in targetcli to update the size value, maybe a new command.

I'm just starting to think about this, please let me know your thoughts on how we might best make this possible and straightforward.

**Comment by pcuzner** [comment]
Almost. After extending the file, and then updating the dev_size I can query the size of the LUN from targetcli correctly which is great - BUT, I can't get the change propogated to the client.

On the client, I did the following
rescan the iscsi connections
rescan the physical paths (/dev/sdX)
rescan multipath
check lsblk - shows the old size still

I also logged out of the iscsi connection entirely and reconnected...same thing - the client is only seeing the old size.

If I'm missing something, please let me know.

**Comment by pkalever** [comment]
Even I have tried this, it didn't work without a target restart.

1. Expanded the file, updated the dev_size and to have it persisted on disk did targetcli saveconfig, I can query the size and get the new size with targetcli info.

2. On client, rescan the iSCSI connections, this did not shown me the new size 

Now, I went a step ahead and restarted the target, then rescan the iSCSI connections, lsblk  shows me the new size.

**Comment by agrover** [comment]
sorry for the extreme delay, sometimes I freeze up, when working on issues that I don't have an immediate answer for :frowning: 

In this case, I think it's because in tcmu-runner's glfs.c only gets the size when it opens the backstore, and then saves it.

I think https://github.com/open-iscsi/tcmu-runner/pull/60 will fix this issue, if you'd like to try that.

**Comment by pkalever** [comment]
I have tried this fix today, and it worked!

On server, Increase the size and update it in
"/sys/kernel/config/target/core/user_0/glfsLUN/control"
On the client, rescan the iscsi connections, rescan multipath, check
lsblk - shows the new size

Also Find the attachment for detailed steps and result
[resize-steps.txt](https://github.com/open-iscsi/targetcli-fb/files/394377/resize-steps.txt)

**Comment by pkalever** [comment]
Now we have an option 'dev_size' to tune size:

_Target side,_

**[root@localhost ~]# targetcli /backstores/user:glfs/ ls**                                                  
o- user:glfs .................................................................................................. [Storage Objects: 1]                                                                               
  o- block ............................ [sample@192.168.124.113/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b (1.0GiB) activated]                                                                               
    o- alua ....................................................................................................... [ALUA Groups: 0]                                                                               

**[root@localhost ~]# targetcli /backstores/user:glfs/block get attribute dev_size**                         
dev_size=1073741824                                 

**[root@localhost ~]# cat /sys/kernel/config/target/core/user_0/block/info**                                 
Status: ACTIVATED  Max Queue Depth: 0  SectorSize: 512  HwMaxSectors: 128                                
        Config: glfs/sample@192.168.124.113/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b Size: 1073741824 MaxDataAreaMB: 8                                                                                     

**[root@localhost ~]# ls -l /mnt/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b**                          
-rw-------. 1 root root 1073741824 Nov 17 17:22 /mnt/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b    


_Initiator side,_

**root@localhost ~]# iscsiadm -m discovery -t st -p 192.168.124.113**                                                                                                                                                 
192.168.124.113:3260,1 iqn.2016-12.org.gluster-block:f82079f0-b2b4-4746-87f3-b5818949ed2b                

**[root@localhost ~]# iscsiadm -m node -T "iqn.2016-12.org.gluster-block:f82079f0-b2b4-4746-87f3-b5818949ed2b" -l**
Logging in to [iface: default, target: iqn.2016-12.org.gluster-block:f82079f0-b2b4-4746-87f3-b5818949ed2b, portal: 192.168.124.113,3260] (multiple)                                                                
Login to [iface: default, target: iqn.2016-12.org.gluster-block:f82079f0-b2b4-4746-87f3-b5818949ed2b, portal: 192.168.124.113,3260] successful.                                                                    

**[root@localhost ~]# lsblk**                           
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT    
sda             8:0    0  20G  0 disk               
├─sda1          8:1    0   1G  0 part /boot         
└─sda2          8:2    0  19G  0 part               
  ├─rhgs-root 253:0    0  17G  0 lvm  /             
  └─rhgs-swap 253:1    0   2G  0 lvm  [SWAP]        
sdb             8:16   0   1G  0 disk               


_Now increased backend size on the target side,_

**[root@localhost ~]# truncate -s +1G /mnt/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b**                

**[root@localhost ~]# ls -l /mnt/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b**                                                                                                                                    
-rw-------. 1 root root 2147483648 Nov 17 17:24 /mnt/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b    

**[root@localhost ~]# targetcli /backstores/user:glfs/block set attribute dev_size=2147483648**                                                                                                                        
Parameter dev_size is now '2147483648'.             

**[root@localhost ~]# cat /sys/kernel/config/target/core/user_0/block/info**                                                                                                                                           
Status: ACTIVATED  Max Queue Depth: 0  SectorSize: 512  HwMaxSectors: 128                                
        Config: glfs/sample@192.168.124.113/block-store/f82079f0-b2b4-4746-87f3-b5818949ed2b Size: 2147483648 MaxDataAreaMB: 8                                                                                     


_Back to initator for re-scanning the iscsi connections,_

**[root@localhost ~]# iscsiadm -m node -R**             
Rescanning session [sid: 14, target: iqn.2016-12.org.gluster-block:f82079f0-b2b4-4746-87f3-b5818949ed2b, portal: 192.168.124.113,3260]                                                                             

**[root@localhost ~]# lsblk**
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT    
sda             8:0    0  20G  0 disk               
├─sda1          8:1    0   1G  0 part /boot         
└─sda2          8:2    0  19G  0 part               
  ├─rhgs-root 253:0    0  17G  0 lvm  /             
  └─rhgs-swap 253:1    0   2G  0 lvm  [SWAP]        
sdb             8:16   0   2G  0 disk   --------------------------> ** Note size did grow! **



@agrover should we close this issue now ?

**Comment by agrover** [comment]
sure!
