### ISSUE TITLE
targetcli should not require TARGET_CORE built as a module

### ISSUE THREAD

**Issue by diogocp** [open-iscsi/targetcli-fb#64]
I have TARGET_CORE built-in. When I run target-cli, I get this error:

> b"modprobe: ERROR: could not insert 'target_core_mod': Invalid argument\n"

**Comment by agrover** [comment]
Does your distro have python-kmod? If that's installed then we use that instead of modprobe, and that should not complain when something is built-in, I think.

**Comment by diogocp** [comment]
After installing python-kmod the error message changes to
> Could not modprobe

IIRC, it also complains about missing /proc/modules when the kernel doesn't have loadable module support.

**Comment by agrover** [comment]
This is actually an open-scsi/rtslib-fb bug, I've just pushed a proposed fix over there if you want to test.

**Comment by diogocp** [comment]
Working great with rtslib-fb master, thanks!
