### ISSUE TITLE
RFC: remove packaging from upstream

### ISSUE THREAD

**Issue by cvubrugier** [open-iscsi/targetcli-fb#69]
With the Debian packaging initiative making progress, I think it is time to maybe reconsider the future of our in-repo packaging.

Debian packagers have reported in the past that having a "debian" directory makes their work harder when merging the upstream branch into their packaging branch. Moreover, our in-repo Debian packaging is less complete than the "soon to be ready" Debian packaging. The same remark may apply to our in-repo RPM packaging.

Maybe it is time to drop our in-repo packaging and invite people to install the targetcli-fb package from their distro in our README.md. We could replace the "in-repo packaging" section with a list of distributions that ship targetcli-fb (RHEL, Fedora, Suse, Archlinux, and soon Debian).

What do you think?

**Comment by agrover** [comment]
Sounds pretty good to me. If people need an example of how to build a .deb then we can just link to the actual Debian scripts maybe.

**Comment by gonzoleeman** [comment]
I like this idea. We should either fully support distro-specific packaging or do away with it. Would it be worth keeping around the current debian stuff in some sort of "example" directory, for those that are trying to roll their own?

**Comment by aarcane** [comment]
okay, I finally found this bug.  It's an attrocious idea.  that packaging is important for any of us who are using targetcli but aren't actively using our distro's supported version.  Leave it in, or revert this pull.  It's a headache, and it'll cause more problems than it could possibly fix.

**Comment by agrover** [comment]
let's use https://github.com/open-iscsi/rtslib-fb/issues/83 for our discussion, ok?
