### ISSUE TITLE
Can you add more examples how to interact with user backend?

### ISSUE THREAD

**Issue by Nefelim4ag** [open-iscsi/targetcli-fb#79]
I've give a try to user:file_async
```
/backstores/user:file_async> create name=test size=1G cfgstring=/tmp/1
'size', 'level', and 'config' must be set when creating a new UserBackedStorageObject
```
and i don't find a way to specify 'level'
tcmu-runner with strace show me:
```
access("/tmp/1", W_OK)                  = 0
Mar 15 18:29:38 ceph-osd-01 strace[26439]: write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
```

May be i miss understand something? Please add some examples.

Thanks

**Comment by mikechristie** [comment]
I do not see level and config. What version of targetcli and rtslib are you using? Are they distro builds or upstream from github?

For the upstream fb tree (https://github.com/open-iscsi/targetcli-fb), I see:

/backstores/user:file> create 
cfgstring=  name=  size=  wwn=    

for the creation options, and I get this when creating:

/backstores/user:file> create cfgstring=/work/luns/lun0 name=filetest size=1G
Created user-backed storage object filetest size 1073741824.

**Comment by mikechristie** [comment]
But yeah, will update the docs with examples on how to use targetcli.

**Comment by mikechristie** [comment]
Oh shoot. Sorry, I thought this issue was posted on the tcmu-runner github.

I meant I would add examples in the tcmu-runner docs.

And, I guess the version you are using is from here :)

**Comment by Nefelim4ag** [comment]
FYI:
# apt-cache policy targetcli-fb 
targetcli-fb:
  Installed: 2.1.43-1
  Candidate: 2.1.43-1
  Version table:
 *** 2.1.43-1 500
        500 http://by.archive.ubuntu.com/ubuntu zesty/universe amd64 Packages

So, as i didn't check tool version, i will try update it to latest tag %) and retest

**Comment by Nefelim4ag** [comment]
Thanks for the info, with last version of targetcli-fb stack all working good
