### ISSUE TITLE
Backups only written if backup directory exists.

### ISSUE THREAD

**Issue by chris-se** [open-iscsi/targetcli-fb#80]
The following bug has recently been reported in the Debian bugtracker:
https://bugs.debian.org/858459

The problem is that targetcli claims on exit (and when manually saving) that a backup file was written, but in reality any error when writing the file is simply ignored.

I don't think it's necessarily wrong to not fail with an error here, but at least a warning message should be printed if the backup file could not be written.

Furthermore it might be prudent to try to create the backup directory if it doesn't already exist.

I'll happily provide a patch (+ pull request) for adding the warning message, but before I do so I'd like to know if you'd be in favor of auto-creating the backup directory if it doesn't already exist.

**Comment by agrover** [comment]
I think it's slightly preferable that the packaging create the backups dir, but if it's not there, and creating it will allow targetcli to successfully back up its config, then yes, creating it seems like the most user friendly thing to do. Thanks!
